### PR TITLE
Demo of custom typography variants in react/mui

### PR DESCRIPTION
**Pull request by mmigdol**
To dissuade the team from using "h1", "h2" etc which are pretty antiquated concepts, I am encouraging them to use custom variants like "dialogTitle" instead.

image

[MUI Typography](https://mui.com/material-ui/api/typography/) has a fairly limited set of variants, but it's easy to add our own to our theme, as illustrated by this demo.

### CODE REVIEW

**Comment by bellatinyfish** [comment]
Thanks for doing this customization ! 
This makes sense, using Typography variant is much more flexible than global overriding

**Review by bellatinyfish — APPROVED** [review]

**Review by thakkerurvish — CHANGES_REQUESTED** [review]
Fish-tank is a public repository and it is aimed to be a warehouse of `AgentQL` examples. I am not sure what is the proposed PR and why does it belong here.

**Comment by bellatinyfish** [comment]
Looks like this is using MUI 5, but we are using MUI4. 
Tried to find a way to implement something similar to this using MUI4, but seems like it doesn't work with MUI 4 ?

**Comment by paveldudka** [comment]
> Fish-tank is a public repository and it is aimed to be a warehouse of `AgentQL` examples. I am not sure what is the proposed PR and why does it belong here. 

I think it was meant to be pushed to tf-tutorials repo. Not here

**Comment by mmigdol** [comment]
> > Fish-tank is a public repository and it is aimed to be a warehouse of `AgentQL` examples. I am not sure what is the proposed PR and why does it belong here. 
> 
> I think it was meant to be pushed to tf-tutorials repo. Not here

Whoops sloppy.  Sorry about that

**Pull request closed without merging**
